"""llm-router: 零依赖的 OpenAI 兼容模型智能调度器。"""
from . import executor, policy, preferences, quota, router, scheduler, task
from .policy import (
    DEFAULT_MODEL_POLICIES,
    QUOTA_WINDOW_SECONDS,
    ModelPolicy,
    atomic_write_json,
    configure_state_dir,
    default_state_dir,
    get_policy,
    get_policy_path,
    get_quota_table,
    get_state_dir,
    get_language,
    is_peak_hour,
    list_models,
    resolve_model,
    find_by_role,
    update_policy,
)
from .quota import (
    COOLDOWN_SECONDS,
    WINDOW_SECONDS,
    QuotaTracker,
    cooldown_seconds_left,
    quota_left,
    quota_table_left,
    record_call,
    record_failure,
    reset_if_needed,
)
from .router import (
    ModelRouter,
    assess_difficulty,
    assess_urgency,
    format_model_key,
    format_selector_key,
    parse_model_key,
    parse_selector_key,
    recommend_for_session,
    route_model,
)
from .task import (
    VALID_PRIORITIES,
    VALID_STATUSES,
    Task,
    TaskStore,
    valid_transition,
)
from .scheduler import (
    DEFAULT_BASE_DELAY,
    DEFAULT_DEADLINE_HORIZON,
    DEFAULT_MAX_RETRIES,
    PRIORITY_WEIGHTS,
    TaskScheduler,
)
from .executor import (
    CommandExecutor,
    Executor,
    ExecutorResult,
    MockExecutor,
)
from .preferences import (
    DEFAULT_WEIGHTS,
    VALID_MODES,
    WEIGHT_KEYS,
    Preferences,
    PreferencesStore,
)

__version__ = "0.3.0"

__all__ = [
    "ModelPolicy",
    "QuotaTracker",
    "ModelRouter",
    "assess_difficulty",
    "assess_urgency",
    "route_model",
    "recommend_for_session",
    "format_model_key",
    "format_selector_key",
    "parse_model_key",
    "parse_selector_key",
    "get_policy",
    "list_models",
    "resolve_model",
    "find_by_role",
    "get_language",
    "is_peak_hour",
    "get_quota_table",
    "update_policy",
    "atomic_write_json",
    "configure_state_dir",
    "default_state_dir",
    "get_state_dir",
    "get_policy_path",
    "record_call",
    "quota_left",
    "reset_if_needed",
    "quota_table_left",
    "record_failure",
    "cooldown_seconds_left",
    "DEFAULT_MODEL_POLICIES",
    "QUOTA_WINDOW_SECONDS",
    "WINDOW_SECONDS",
    "COOLDOWN_SECONDS",
    "Task",
    "TaskStore",
    "valid_transition",
    "VALID_PRIORITIES",
    "VALID_STATUSES",
    "TaskScheduler",
    "DEFAULT_BASE_DELAY",
    "DEFAULT_DEADLINE_HORIZON",
    "DEFAULT_MAX_RETRIES",
    "PRIORITY_WEIGHTS",
    "Executor",
    "ExecutorResult",
    "MockExecutor",
    "CommandExecutor",
    "Preferences",
    "PreferencesStore",
    "DEFAULT_WEIGHTS",
    "VALID_MODES",
    "WEIGHT_KEYS",
    "policy",
    "quota",
    "router",
    "task",
    "scheduler",
    "executor",
    "preferences",
]
